language: node_js
node_js:
  - 17
addons:
  sonarcloud:
    organization: x8163don
    token:
      secure: 0728e669f3961aa8fc144e27c1df5b9aa7d76268
cache:
  directories:
    - node_modules

before_deploy:
  - "export NODE_OPTIONS=--openssl-legacy-provider"
  - "npm run build"

script: echo "npm test disabled"

install:
  - yarn

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
